### ISSUE TITLE
Downloaded XLSX files would occasionally be corrupt.

### ISSUE THREAD

**Issue by Jia265** [dtjohnson/xlsx-populate#114] opened 2018-02-16 20:42 UTC
I'm uncertain if this is an issue with XLSX-populate or something different all together. 

But I've tried using the export examples mentioned on the read me using the below section of code

`workbook.outputAsync()
    .then(function (blob) {
        if (window.navigator && window.navigator.msSaveOrOpenBlob) {
            // If IE, you must uses a different method.
            window.navigator.msSaveOrOpenBlob(blob, "out.xlsx");
        } else {
            var url = window.URL.createObjectURL(blob);
            var a = document.createElement("a");
            document.body.appendChild(a);
            a.href = url;
            a.download = "out.xlsx";
            a.click();
            window.URL.revokeObjectURL(url);
            document.body.removeChild(a);
        }
    });`

However I would occasionally get files that are corrupted. It would be extremely inconsistent in the behavior. I could download the same blob (saved in console) several times to have different results. 

I'm not completely certain if this is related to the blob itself, or something other all together.

If it's not I apologize for making an off topic post.

**Comment by Jia265** [comment] 2018-05-15 18:29
@Robophil 
It's been a while since I did this, but if I remember correctly the issue was that the file wasn't actually finished downloading despite chrome saying that it was. 

What did was that I would download the file, open it IMMEDIATELY. It would almost always fail (without fail... lol). But then if you wait a few seconds (or longer if your file is larger) then you try to open the same exact file that failed just moments earlier, it will now work. 

I'm still not certain if this is an issue related to XLSX-populate or the browser, but just advice a bit of patience and let the download run it's course and it will be fine.

**Comment by Robophil** [comment] 2018-05-17 09:15
I've noticed this happens when I open the sheet and no condition passes that would require me updating the sheet. Calling `workbook.outputAsync()` would output the corrupt file

**Comment by dtjohnson** [comment] 2019-03-01 01:32
I'm going to close this as unable to reproduce.

**Closed by dtjohnson** 2019-03-01 01:32 UTC
