### ISSUE TITLE
ArgHandler error on Webpack/UglifyJS build

### ISSUE THREAD

**Issue by rdubbeldam86** [dtjohnson/xlsx-populate#74] opened 2017-08-04 09:03 UTC
Using the latest versions of 
NodeJS
VueJS
Webpack
xlsx-populate

When running the build option we get an error on the pages including xlsx-populate. 
![image](https://user-images.githubusercontent.com/24374408/28961599-2cce52ca-7903-11e7-9dd8-7998bfd7ccda.png)

We also got a 'Can't resolve fs' error on the dev build. We fixed this by adding the following to the webpack config:
  node: {
    fs: 'empty',
  }

This solution was provided for the same issue in another package:
https://github.com/webpack-contrib/css-loader/issues/447 

Could these 2 issues be related to each other?

Steps to reproduce:
Setup new project using the vue-cli (default webpack project)
Install xlsx-populate
run 'npm run build' to create the production files. This should give you the error(s).

Or download the zip with sample project (without node_modules folder).
[test.zip](https://github.com/dtjohnson/xlsx-populate/files/1199780/test.zip)

And run 'npm install' followed by 'npm run build'

**Comment by dtjohnson** [comment] 2017-08-05 12:33
Hmmm.... I'm not sure what the issue is. The fs empty config is expected as we used Node's fs (if available) to load/write files. I'm able to get webpack to work fine by itself:
![image](https://user-images.githubusercontent.com/218771/28995492-93d32da0-79b8-11e7-9b2e-1d9d9c6448c7.png)

Here's my index.js:
```js
import XlsxPopulate from 'xlsx-populate';
```

And here's my webpack.config.js:
```js
module.exports = {
  node: {
    fs: 'empty'
  }
};
```

**Comment by dtjohnson** [comment] 2017-08-17 00:30
I'm going to close this since I can't reproduce. Please reopen if you can provide more detail.

**Closed by dtjohnson** 2017-08-17 00:30 UTC

**Comment by vickdayaram** [comment] 2018-04-09 18:12
Hi, I am actually running into the above issue, and I am not sure how to solve it. Here is the error that I am getting: 

ERROR in app-9c9bcdfb7ba5099216d1.js from UglifyJs
Unexpected token: name (ArgHandler) [../node_modules/xlsx-populate/lib/ArgHandler.js:9,0][app-9c9bcdfb7ba5099216d1.js:122005,6] 

I am able to run npm run buildlib, but when I run npm run build I get this error. 

I updated the webpack config with: 

node: {fs: 'empty'} 

This got rid of the initial error that allowed me to work with the library. 

For my index.js I am using the following to access xlsx-populate: 

import * as XlsxPopulate from 'xlsx-populate' 

I am using typescript which is why I am using that syntax. 

Any help would be greatly appreciated, thanks!

**Comment by vickdayaram** [comment] 2018-04-09 18:33
Never mind, after digging a bit deeper I found my problem, in a previous question. 

https://github.com/dtjohnson/xlsx-populate/issues/105 

If anyone else is having this issue, what solved it for me was updating the import statement to the following: 

import * as XlsxPopulate from 'xlsx-populate/browser/xlsx-populate';

Thanks for the help!

**Comment by nitsanavni** [comment] 2019-03-27 15:29
@vickdayaram worked for me too. Thanks!
